tupla = ('Casa','2',345,'Perro',99)
print("Elementos de la tupla: ",tupla)
print("Elemento de la posición 0: ",tupla[0])
print("Elemento de la posición 1: ",tupla[1])
print("Elemento de la posición 2: ",tupla[2])
print("Elemento de la posición 3: ",tupla[3])
print("Elemento de la posición 4: ",tupla[4])
